version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - server.js
    - package.json
    - package-lock.json
    - templates_files/buildspec.yaml
    - templates_files/appspec.yaml
    - scripts/start-service.sh
    - scripts/stop-service.sh
    - scripts/install.sh
    - 'node_modules/**/*'
