AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair
    Default: aws-bootstrap  # optional default
  EC2InstanceType:
    Type: String
  EC2AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>' # This is a special parameter type that allows our template to get the latest AMI without having to specify the exact version...
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-6.1-x86_64'
  CodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artifacts.'
  GitHubOwner:
    Type: String
    Description: 'The username of the source GitHub repo.'
  GitHubRepo:
    Type: String
    Description: 'The source GitHub repo name (without the username).'
  GitHubBranch:
    Type: String
    Default: main
    Description: 'The source GitHub branch.'
  GitHubPersonalAccessToken:
    Type: String
    NoEcho: true
    Description: 'A GitHub personal access token with "repo" and "admin:repo_hook" permissions.'  
  
Resources:
  CodePipelineS3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref CodePipelineBucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}' # !Sub is a CloudFormation function that performs string interpolation...AWS::StackName is a CloudFormation pseudo parameter...

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          Value: !Ref AWS::StackName # !Ref is a CloudFormation function for referring to other resources in your stack...

  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - "ec2.amazonaws.com"
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy # Allows our EC2 instance to access CodeDeploy.

      Tags:
        - Key: Name
          Value: !Ref AWS::StackName 

  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com
              - codedeploy.amazonaws.com
              - codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess # allow codebuild,codedeploy and codepipeline to access aws resources       

  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - Ref: InstanceRole 

  Instance:
    Type: AWS::EC2::Instance
    # CreationPolicy: # This tells CloudFormation to wait for a signal before marking the new instance as created...
    #   ResourceSignal:
    #     Timeout: PT15M
    #     Count: 1
    # Metadata:
      # AWS::CloudFormation::Init:
      #   config:
      #     packages: # Here we define some prerequisites that CloudFormation will install on our instance (the wget and unzip utilities)
      #       yum:
      #         wget: []
      #         unzip: []
      #         ruby: []
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref EC2AMI # The AMI ID that we take as a template parameter.
      InstanceType: !Ref EC2InstanceType # The EC2 instance type that we take as a template parameter.
      IamInstanceProfile: !Ref InstanceProfile
      Monitoring: true
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId # !GetAtt is a CloudFormation function that can reference attributes from other resources... 
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # Update system
          dnf update -y

          # Install Node and PM2
          dnf install -y nodejs npm
          npm install -g pm2

          # Install CodeDeploy agent (Amazon Linux 2023)
          dnf install -y ruby wget
          cd /tmp
          wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
          chmod +x install
          ./install auto
          systemctl enable codedeploy-agent
          systemctl start codedeploy-agent

          # Prepare an application directory for CodeDeploy
          mkdir -p /home/ec2-user/app/release
          chown -R ec2-user:ec2-user /home/ec2-user/app  

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${AWS::StackName}-CodeBuild"
      ServiceRole: !GetAtt DeploymentRole.Arn   # must allow codebuild actions
      Artifacts:
        Type: CODEPIPELINE                    # output goes to CodePipeline
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0     # Updated: standard 2.0 is deprecated
        PrivilegedMode: false                 # or true if using Docker builds
      Source:
        Type: CODEPIPELINE 
        BuildSpec: templates_files/buildspec.yaml  # <-- specify path here                   # input comes from CodePipeline
      TimeoutInMinutes: 15
      Cache:
        Type: NO_CACHE                        # optional: S3 cache can be added
      Description: Build project for CI/CD pipeline

  DeploymentApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref AWS::StackName
      ComputePlatform: Server   

  StagingDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: Instance
    Properties:
      DeploymentGroupName: staging
      ApplicationName: !Ref DeploymentApplication
      DeploymentConfigName: CodeDeployDefault.AllAtOnce   #  Deploy strategy
      ServiceRoleArn: !GetAtt DeploymentRole.Arn
      Ec2TagFilters:                                       # EC2 selection via tags
        - Key: aws:cloudformation:stack-name
          Type: KEY_AND_VALUE
          Value: !Ref AWS::StackName  

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref AWS::StackName
      RoleArn: !GetAtt DeploymentRole.Arn

      ArtifactStore:
        Type: S3
        Location: !Ref CodePipelineBucket

      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: Source
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubPersonalAccessToken
                PollForSourceChanges: false   # â¶ Using webhooks instead of polling
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: Build
              Configuration:
                ProjectName: !Ref BuildProject
              RunOrder: 1

        - Name: Staging
          Actions:
            - Name: Staging
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              InputArtifacts:
                - Name: Build
              Configuration:
                ApplicationName: !Ref DeploymentApplication
                DeploymentGroupName: !Ref StagingDeploymentGroup
              RunOrder: 1  

  PipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Name: !Sub "webhook-${AWS::StackName}"
      TargetPipeline: !Ref Pipeline
      TargetPipelineVersion: !GetAtt Pipeline.Version
      TargetAction: Source

      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubPersonalAccessToken

      RegisterWithThirdParty: true

      Filters:
        - JsonPath: $.ref
          MatchEquals: "refs/heads/{Branch}"                     

Outputs:
  InstanceEndpoint:
    Description: The DNS name for the created instance
    Value: !Sub "http://${Instance.PublicDnsName}:8080" # This creates a URL for the endpoint of the instance
    Export:
      Name: InstanceEndpoint